const airtableResponse = {
    "id":"PO-4660",
    "items":[
        {
            "id":"tnen_po-12",
            "masterSku":"TNEN_PO-12",
            "masterQty":"50",
            "listings":[
                {
                    "id":"tnen_po-12_1523469411119",
                    "masterSku":"TNEN_PO-12",
                    "listingSku":"TNEN_PO-12",
                    "listingQty":"50",
                    "sendToFBA":true,
                    "parent":"tnen_po-12"
                }
            ]
        },
        {
            "id":"tnen_po-20",
            "masterSku":"TNEN_PO-20",
            "masterQty":"140",
            "listings":[
                {
                    "id":"tnen_po-20_1523469411119",
                    "masterSku":"TNEN_PO-20",
                    "listingSku":"TNEN_PO-20",
                    "listingQty":"140",
                    "sendToFBA":true,
                    "parent":"tnen_po-20"
                }
            ]
        },
        {
            "id":"tnen_po-33",
            "masterSku":"TNEN_PO-33",
            "masterQty":"80",
            "listings":[
                {
                    "id":"tnen_po-33_1523469411119",
                    "masterSku":"TNEN_PO-33",
                    "listingSku":"TNEN_PO-33",
                    "listingQty":"80",
                    "sendToFBA":true,
                    "parent":"tnen_po-33"
                }
            ]
        },
        {
            "id":"tnen_po-35",
            "masterSku":"TNEN_PO-35",
            "masterQty":"80",
            "listings":[
                {
                    "id":"tnen_po-35_1523469411119",
                    "masterSku":"TNEN_PO-35",
                    "listingSku":"TNEN_PO-35",
                    "listingQty":"80",
                    "sendToFBA":true,
                    "parent":"tnen_po-35"
                }
            ]
        },
        {
            "id":"tnen_ca-12",
            "masterSku":"TNEN_CA-12",
            "masterQty":"10",
            "listings":[
                {
                    "id":"tnen_ca-12_1523469411119",
                    "masterSku":"TNEN_CA-12",
                    "listingSku":"TNEN_CA-12",
                    "listingQty":"10",
                    "sendToFBA":true,
                    "parent":"tnen_ca-12"
                }
            ]
        },
        {
            "id":"tnen_po-14",
            "masterSku":"TNEN_PO-14",
            "masterQty":"50",
            "listings":[
                {
                    "id":"tnen_po-14_1523469411119",
                    "masterSku":"TNEN_PO-14",
                    "listingSku":"TNEN_PO-14",
                    "listingQty":"50",
                    "sendToFBA":true,
                    "parent":"tnen_po-14"
                }
            ]
        },
        {
            "id":"tnen_ca-14",
            "masterSku":"TNEN_CA-14",
            "masterQty":"10",
            "listings":[
                {
                    "id":"tnen_ca-14_1523469411119",
                    "masterSku":"TNEN_CA-14",
                    "listingSku":"TNEN_CA-14",
                    "listingQty":"10",
                    "sendToFBA":true,
                    "parent":"tnen_ca-14"
                }
            ]
        },
        {
            "id":"tnen_po-16",
            "masterSku":"TNEN_PO-16",
            "masterQty":"10",
            "listings":[
                {
                    "id":"tnen_po-16_1523469411119",
                    "masterSku":"TNEN_PO-16",
                    "listingSku":"TNEN_PO-16",
                    "listingQty":"10",
                    "sendToFBA":true,
                    "parent":"tnen_po-16"
                }
            ]
        },
        {
            "id":"tnen_ca-16",
            "masterSku":"TNEN_CA-16",
            "masterQty":"10",
            "listings":[
                {
                    "id":"tnen_ca-16_1523469411119",
                    "masterSku":"TNEN_CA-16",
                    "listingSku":"TNEN_CA-16",
                    "listingQty":"10",
                    "sendToFBA":true,
                    "parent":"tnen_ca-16"
                }
            ]
        },
        {
            "id":"tnen_po-24",
            "masterSku":"TNEN_PO-24",
            "masterQty":"20",
            "listings":[
                {
                    "id":"tnen_po-24_1523469411119",
                    "masterSku":"TNEN_PO-24",
                    "listingSku":"TNEN_PO-24",
                    "listingQty":"20",
                    "sendToFBA":true,
                    "parent":"tnen_po-24"
                }
            ]
        },
        {
            "id":"tnen_ca-24",
            "masterSku":"TNEN_CA-24",
            "masterQty":"10",
            "listings":[
                {
                    "id":"tnen_ca-24_1523469411119",
                    "masterSku":"TNEN_CA-24",
                    "listingSku":"TNEN_CA-24",
                    "listingQty":"10",
                    "sendToFBA":true,
                    "parent":"tnen_ca-24"
                }
            ]
        },
        {
            "id":"tnen_po-28",
            "masterSku":"TNEN_PO-28",
            "masterQty":"10",
            "listings":[
                {
                    "id":"tnen_po-28_1523469411119",
                    "masterSku":"TNEN_PO-28",
                    "listingSku":"TNEN_PO-28",
                    "listingQty":"10",
                    "sendToFBA":true,
                    "parent":"tnen_po-28"
                }
            ]
        },
        {
            "id":"tnen_ca28",
            "masterSku":"TNEN_CA28",
            "masterQty":"15",
            "listings":[
                {
                    "id":"tnen_ca28_1523469411119",
                    "masterSku":"TNEN_CA28",
                    "listingSku":"TNEN_CA28",
                    "listingQty":"15",
                    "sendToFBA":true,
                    "parent":"tnen_ca28"
                }
            ]
        },
        {
            "id":"tnen_po-32",
            "masterSku":"TNEN_PO-32",
            "masterQty":"50",
            "listings":[
                {
                    "id":"tnen_po-32_1523469411119",
                    "masterSku":"TNEN_PO-32",
                    "listingSku":"TNEN_PO-32",
                    "listingQty":"50",
                    "sendToFBA":true,
                    "parent":"tnen_po-32"
                }
            ]
        },
        {
            "id":"tnen_ca-x",
            "masterSku":"TNEN_CA-X",
            "masterQty":"30",
            "listings":[
                {
                    "id":"tnen_ca-x_1523469411119",
                    "masterSku":"TNEN_CA-X",
                    "listingSku":"TNEN_CA-X",
                    "listingQty":"30",
                    "sendToFBA":true,
                    "parent":"tnen_ca-x"
                }
            ]
        },
        {
            "id":"tnen_ca20",
            "masterSku":"TNEN_CA20",
            "masterQty":"40",
            "listings":[
                {
                    "id":"tnen_ca20_1523469411119",
                    "masterSku":"TNEN_CA20",
                    "listingSku":"TNEN_CA20",
                    "listingQty":"40",
                    "sendToFBA":true,
                    "parent":"tnen_ca20"
                }
            ]
        },
        {
            "id":"tnen_mc-3",
            "masterSku":"TNEN_MC-3",
            "masterQty":"20",
            "listings":[
                {
                    "id":"tnen_mc-3_1523469411119",
                    "masterSku":"TNEN_MC-3",
                    "listingSku":"TNEN_MC-3",
                    "listingQty":"20",
                    "sendToFBA":true,
                    "parent":"tnen_mc-3"
                }
            ]
        },
        {
            "id":"tnen_po-30",
            "masterSku":"TNEN_PO-30",
            "masterQty":"20",
            "listings":[
                {
                    "id":"tnen_po-30_1523469411119",
                    "masterSku":"TNEN_PO-30",
                    "listingSku":"TNEN_PO-30",
                    "listingQty":"20",
                    "sendToFBA":true,
                    "parent":"tnen_po-30"
                }
            ]
        }
    ],
    "additionalNotes":" - TNEN_PO-12\n      40 for MIXB_A137\n      10 for MIXB_A502\n \n- TNEN_PO-20\n      60 for MIXB_A139\n      10 for MIXB_A505\n       70 for TNEN_PO-20\n\n - TNEN_PO-33\n      10 for MIXB_A500\n      10 for MIXB_A509\n      60 for TNEN_PO-33\n\n - TNEN_PO-35\n       10 for MIXB_A501\n        10 for MIXB_A510\n       60 for TNEN_PO-35\n\nTNEN_CA-12\nfor bundles\n\n50 - TNEN_PO-14\n        40 for TNEN_PO-14\n       10 for MIXB_A503\n\nTNEN_CA-14\nfor bundles\n\n10 - TNEN_PO-16\n       for MIXB_A504\n\n10 - TNEN_CA-16\n      for bundles\n\n110 - TNEN_CA-20\n       100 for TNEN_CA-20\n       rest for bundles\n\n - TNEN_PO-24\n      10 for MIXB_A506\n      10 for MIXB_A511\n\n10 - TNEN_CA-24\n       for bundles\n\n - TNEN_PO-28\n    10 for TNEN_PO-28\n\nTNEN_CA28\n5 for TNEN_CA28\nrest for bundles\n\n- TNEN_PO-32\n     10 for MIXB_A508\n      40 for TNEN_PO-32\n\nTNEN_CA-X\n10 for TNEN_CA-X\nrest for bundles"
}
